### ISSUE TITLE
Script does not update automatically

### ISSUE THREAD

**Issue by ShinonomeLab** [MadaraUchiha/star-thumn#17]
check this out on how to add it:
http://stackoverflow.com/questions/15095055/why-isnt-my-greasemonkey-script-updating

**Comment by ShinonomeLab** [comment]
Looks like some userscript extensions (tampermonkey, greasemonkey, whatever for IE) might not be updating styles automatically (caching maybe). To update everything properly, they need to be deleted and new ones installed. Automatic update should remove the need for that workaround.

**Comment by somebody1234** [comment]
Automatic update doesn't update styles for me

**Comment by somebody1234** [comment]
_Should_ be fixed.
