### ISSUE TITLE
Needs README

### ISSUE THREAD

**Issue by MadaraUchiha** [MadaraUchiha/star-thumn#3]
Would appreciate someone contributing to this

**Comment by ShinonomeLab** [comment]
This is a userscript for StackExchange chat. It replaces all direct links to images in starred messages widget with thumbnails of said images.

![](http://i.stack.imgur.com/GA1oC.png)

It also shows the star counter on hover and allows you to star/unstar images.

![](http://i.stack.imgur.com/A0I18.gif)

**Comment by MadaraUchiha** [comment]
Closed in #14.
