### ISSUE TITLE
Broken images are broken

### ISSUE THREAD

**Issue by MadaraUchiha** [MadaraUchiha/star-thumn#6]
If an image link is broken, it should either not display or display a replacement.

**Comment by Unihedro** [comment]
+1, see http://chat.stackoverflow.com/transcript/message/22453995#22453995

**Comment by somebody1234** [comment]
@MadaraUchiha this should be fixed as well

**Comment by MadaraUchiha** [comment]
You have collaborator access, feel free to mark it as closed :)
